workflows:
  build_wheelyou_ios:
    name: Build Wheelyou iOS
    environment:
      flutter: "3.37.0-0.1.pre"  # Flutter dev channel with Dart 3.10
      xcode: latest
      cocoapods: default
      android: stable
    scripts:
      # 1. Switch to Flutter dev channel and upgrade
      - name: Switch to Flutter dev channel
        script: |
          flutter channel dev
          flutter upgrade --force

      # 2. Install project dependencies
      - name: Install Flutter dependencies
        script: flutter pub get

      # 3. Clean previous builds (optional, recommended)
      - name: Clean build
        script: flutter clean

      # 4. Run pod install for iOS
      - name: Install iOS pods
        script: |
          cd ios
          pod install
          cd ..

      # 5. Build iOS IPA
      - name: Build iOS IPA
        script: flutter build ios --release --no-codesign

      # 6. Export IPA with proper signing (Codemagic handles signing)
      - name: Export IPA
        script: flutter build ipa --export-options-plist ios/ExportOptions.plist
