workflows:
  build_wheelyou_ios:
    name: Build Wheelyou iOS (Unsigned)
    environment:
      flutter: "stable"
      xcode: latest
      cocoapods: default

    scripts:
      # 1️⃣ Switch to Flutter stable
      - name: Switch to Flutter stable channel
        script: |
          flutter channel stable
          flutter upgrade --force
          flutter --version

      # 2️⃣ Install dependencies
      - name: Install dependencies
        script: flutter pub get

      # 3️⃣ Clean previous builds
      - name: Clean build
        script: flutter clean

      # 4️⃣ Generate iOS configs (if needed)
      - name: Generate iOS configs
        script: flutter pub run build_runner build || true

      # 5️⃣ Install CocoaPods
      - name: Install iOS pods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      # 6️⃣ Build unsigned IPA using Flutter's built-in command
      - name: Build unsigned IPA
        script: |
          flutter build ipa --release --no-codesign \
            --build-name=1.0.0 --build-number=1

    artifacts:
      - build/ios/ipa/*.ipa
