workflows:
  build_wheelyou_ios:
    name: Build Wheelyou iOS
    environment:
      flutter: "3.37.0-0.1.pre"   # dev channel (Dart 3.10)
      xcode: latest
      cocoapods: default
      android: stable
    scripts:
      - name: Switch to Flutter dev channel
        script: |
          flutter channel dev
          flutter upgrade --force

      - name: Install Flutter dependencies
        script: flutter pub get

      - name: Clean build
        script: flutter clean

      - name: Install iOS pods
        script: |
          cd ios
          pod install
          cd ..

      - name: Build iOS app
        script: flutter build ios --release --no-codesign

      - name: Export IPA
        script: flutter build ipa --export-options-plist ios/ExportOptions.plist

artifacts:
  - build/ios/ipa/*.ipa
