workflows:
  build_wheelyou_ios:
    name: Build Wheelyou iOS
    environment:
      flutter: "3.37.0-0.1.pre"   # Cached Flutter dev version with Dart 3.10
      xcode: latest
      cocoapods: default
      android: stable   # only for completeness; not used for iOS
    scripts:
      # 1️⃣ Force dev channel + upgrade
      - name: Switch to Flutter dev channel
        script: |
          flutter channel dev
          flutter upgrade --force

      # 2️⃣ Install Flutter dependencies
      - name: Install Flutter dependencies
        script: flutter pub get

      # 3️⃣ Clean previous builds (recommended)
      - name: Clean build
        script: flutter clean

      # 4️⃣ Install CocoaPods for iOS
      - name: Install iOS pods
        script: |
          cd ios
          pod install
          cd ..

      # 5️⃣ Build iOS app (unsinged)
      - name: Build iOS app
        script: flutter build ios --release --no-codesign

      # 6️⃣ Export IPA (signed or unsigned)
      # Codemagic can handle automatic signing if certificates are configured
      - name: Export IPA
        script: flutter build ipa --export-options-plist ios/ExportOptions.plist

artifacts:
  - build/ios/ipa/*.ipa
