workflows:
  build_wheelyou_ios:
    name: Build Wheelyou iOS (Unsigned)
    environment:
      flutter: "stable"
      xcode: latest
      cocoapods: default

    scripts:
      - name: Build App and Create IPA
        script: |
          # Update bundle identifier
          cd ios
          plutil -replace CFBundleIdentifier -string "wheelyou.mobile.app" Runner/Info.plist
          cd ..
          
          # Build the iOS app
          flutter build ios --release --no-codesign
          
          # Create IPA manually from the .app file
          mkdir -p build/ios/ipa/Payload
          cp -r build/ios/Release-iphoneos/Runner.app build/ios/ipa/Payload/
          cd build/ios/ipa
          zip -r Wheelyou_Unsigned.ipa Payload
          ls -la
          cd ../../..

    artifacts:
      - build/ios/ipa/*.ipa
