workflows:
  build_wheelyou_ios:
    name: Build Wheelyou iOS
    environment:
      flutter: "3.37.0-0.1.pre"   # Cached Flutter dev channel (Dart 3.10)
      xcode: latest
      cocoapods: default
  - name: Switch to Flutter dev channel
    script: |
      flutter channel dev
      flutter upgrade --force
      flutter --version

  - name: Install dependencies
    script: flutter pub get

      # 3️⃣ Clean previous builds
      - name: Clean build
        script: flutter clean

      # 4️⃣ Install CocoaPods for iOS
      - name: Install iOS pods
        script: |
          cd ios
          pod install
          cd ..

      # 5️⃣ Build iOS app (unsigned)
      - name: Build iOS app
        script: flutter build ios --release --no-codesign

      # 6️⃣ Build IPA (Codemagic handles signing if configured)
      - name: Export IPA
        script: flutter build ipa --export-options-plist ios/ExportOptions.plist

artifacts:
  - build/ios/ipa/*.ipa
