workflows:
  build_wheelyou_ios:
    name: Build Wheelyou iOS (Unsigned)
    environment:
      flutter: "stable"      # Use Flutter stable channel
      xcode: latest
      cocoapods: default
    scripts:
      # 1️⃣ Ensure Flutter stable channel
      - name: Switch to Flutter stable channel
        script: |
          flutter channel stable
          flutter upgrade --force
          flutter --version

      # 2️⃣ Install dependencies
      - name: Install dependencies
        script: flutter pub get

      # 3️⃣ Clean previous builds
      - name: Clean build
        script: flutter clean

      # 4️⃣ Install CocoaPods for iOS
      - name: Install iOS pods
        script: |
          cd ios
          pod install
          cd ..

      # 5️⃣ Build Xcode archive without code signing
      - name: Build Xcode archive
        script: flutter build ios --no-codesign

      # 6️⃣ Export unsigned IPA from the archive
      - name: Export unsigned IPA
        script: |
          cd ios
          # Create a minimal ExportOptions.plist for unsigned IPA
          cat > ExportOptions.plist <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>method</key>
    <string>ad-hoc</string>
    <key>signingStyle</key>
    <string>manual</string>
    <key>compileBitcode</key>
    <false/>
    <key>destination</key>
    <string>export</string>
</dict>
</plist>
EOF

          # Export the IPA
          xcodebuild -exportArchive \
            -archivePath build/archive/Runner.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist ExportOptions.plist
          cd ..

artifacts:
  - build/ios/ipa/*.ipa
