workflows:
  build_wheelyou_ios:
    name: Build Wheelyou iOS (Unsigned)
    environment:
      flutter: "stable"
      xcode: latest
      cocoapods: default

    scripts:
      # 1️⃣ Ensure Flutter stable channel
      - name: Switch to Flutter stable channel
        script: |
          flutter channel stable
          flutter upgrade --force
          flutter --version

      # 2️⃣ Install dependencies
      - name: Install dependencies
        script: flutter pub get

      # 3️⃣ Clean previous builds
      - name: Clean build
        script: flutter clean

      # 4️⃣ Generate iOS configs
      - name: Generate iOS configs
        script: flutter pub run build_runner build || true

      # 5️⃣ Install CocoaPods
      - name: Install iOS pods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      # 6️⃣ Build archive
      - name: Build Xcode archive
        script: |
          flutter build ios --release --no-codesign \
            --build-name=1.0.0 --build-number=1

          xcodebuild archive \
            -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath ios/build/Runner.xcarchive \
            CODE_SIGNING_ALLOWED=NO

      # 7️⃣ Export unsigned IPA
      - name: Export unsigned IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath ios/build/Runner.xcarchive \
            -exportOptionsPlist ios/ExportOptions.plist \
            -exportPath build/ios/ipa

    artifacts:
      - build/ios/ipa/*.ipa
