workflows:
  build_wheelyou_ios:
    name: Build Wheelyou iOS (Unsigned)
    environment:
      flutter: "stable"      # Use Flutter stable channel
      xcode: latest
      cocoapods: default
    scripts:
      # 1️⃣ Ensure Flutter stable channel
      - name: Switch to Flutter stable channel
        script: |
          flutter channel stable
          flutter upgrade --force
          flutter --version

      # 2️⃣ Install dependencies
      - name: Install dependencies
        script: flutter pub get

      # 3️⃣ Clean previous builds
      - name: Clean build
        script: flutter clean

      # 4️⃣ Install CocoaPods for iOS
      - name: Install iOS pods
        script: |
          cd ios
          pod install
          cd ..

      # 5️⃣ Build Xcode archive without signing
      - name: Build Xcode archive
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/Runner.xcarchive \
            archive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      # 6️⃣ Export unsigned IPA
      - name: Export unsigned IPA
        script: |
          cd ios
          xcodebuild -exportArchive \
            -archivePath ../build/Runner.xcarchive \
            -exportPath ../build/ios/ipa \
            -exportOptionsPlist ExportOptions.plist \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
          cd ..

artifacts:
  - build/ios/ipa/*.ipa
