workflows:
  build_wheelyou_ios:
    name: Build Wheelyou iOS (Unsigned)
    environment:
      flutter: "stable"      # Use Flutter stable channel
      xcode: latest
      cocoapods: default
    scripts:
      # 1️⃣ Ensure Flutter stable
      - name: Switch to Flutter stable channel
        script: |
          flutter channel stable
          flutter upgrade --force
          flutter --version

      # 2️⃣ Install dependencies
      - name: Install dependencies
        script: flutter pub get

      # 3️⃣ Clean previous builds
      - name: Clean build
        script: flutter clean

      # 4️⃣ Install CocoaPods for iOS
      - name: Install iOS pods
        script: |
          cd ios
          pod install
          cd ..

      # 5️⃣ Build unsigned iOS app
      - name: Build unsigned IPA
        script: flutter build ipa --no-codesign

artifacts:
  - build/ios/ipa/*.ipa
